name: Cloud Build APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v4

      - name: Force Download All Missing Dependencies
        run: |
          # 1. Setup Figma Squircle
          curl -L https://github.com/aloisdeniel/figma_squircle/archive/refs/heads/main.zip -o figma.zip
          unzip figma.zip
          mv figma_squircle-main figma_squircle
          
          # 2. Setup Liquid Progress Indicator
          curl -L https://github.com/PetitPrinc3/liquid_progress_indicator_v2/archive/refs/heads/master.zip -o liquid.zip
          unzip liquid.zip
          mv liquid_progress_indicator_v2-master liquid_progress_indicator_v2

          # 3. Setup Scrobblenaut (The tricky one)
          # We create the directory first to be 100% sure it exists
          mkdir -p scrobblenaut
          curl -L https://github.com/u-9/scrobblenaut/archive/refs/heads/dev.zip -o scrobble.zip
          unzip scrobble.zip -d temp_scrobble
          # This moves the INSIDE contents to your scrobblenaut folder
          cp -r temp_scrobble/scrobblenaut-dev/* scrobblenaut/
          
          # Clean up zips
          rm *.zip
          rm -rf temp_scrobble

      - name: Create API Key File
        run: |
          mkdir -p lib
          cat <<EOF > lib/.env
          deezerGatewayAPI = 'VBK1FSUEXHTSDBJJ';
          deezerMobileKey = '4VCYIJUCDLOUELGD1V8WBVYBNVDYOXEWSLLZDONGBBDFVXTZJRXPR29JRLQFO6ZE';
          lastFmApiKey = '';
          lastFmApiSecret = '';
          acrcloudHost = '';
          acrcloudSongApiKey = '';
          acrcloudSongApiSecret = '';
          acrcloudHumsApiKey = '';
          acrcloudHumsApiSecret = '';
          EOF

      - name: Setup Java & Flutter
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      - name: Final Build
        run: |
          # Use --suppress-analytics to keep logs clean
          flutter pub get
          flutter build apk --release

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: alchemy-final-apk
          path: build/app/outputs/flutter-apk/*.apk
