name: Cloud Build APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Force Submodule Sync (The Fix)
        run: |
          # This forces GitHub to download the missing folders
          git submodule sync --recursive
          git submodule update --init --recursive --force

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      - name: Create API Key File
        run: |
          mkdir -p lib
          cat <<EOF > lib/.env
          deezerGatewayAPI = 'VBK1FSUEXHTSDBJJ';
          deezerMobileKey = '4VCYIJUCDLOUELGD1V8WBVYBNVDYOXEWSLLZDONGBBDFVXTZJRXPR29JRLQFO6ZE';
          lastFmApiKey = '';
          lastFmApiSecret = '';
          acrcloudHost = '';
          acrcloudSongApiKey = '';
          acrcloudSongApiSecret = '';
          acrcloudHumsApiKey = '';
          acrcloudHumsApiSecret = '';
          EOF

      - name: Install Dependencies for All Parts
        run: |
          # This command tells Flutter to look in EVERY folder for dependencies
          flutter pub get
          find . -name "pubspec.yaml" -execdir flutter pub get \;

      - name: Build APK
        run: |
          flutter build apk --split-per-abi --release --no-codesign

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: alchemy-ready-to-install
          path: build/app/outputs/flutter-apk/*.apk
